### ISSUE TITLE
Eye state data is empty

### ISSUE THREAD

**Issue by qian-chu** [pupil-labs/pl-neon-recording#22]
Same intention to play with the [sample data](https://api.cloud.pupil-labs.com/v2/workspaces/3d240903-cbf7-485a-84b1-3498f00e236c/recordings.zip?id=7c141c32-7a8d-411c-9428-70d16de9a9ea&share-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJmY2Q5NWJkYS1lZjVhLTRlN2YtOWZiYi01NTc1NWFhYWQzZTAiLCJtZXRob2QiOiJHRVQiLCJwYXRoIjoiL3YyL3dvcmtzcGFjZXMvM2QyNDA5MDMtY2JmNy00ODVhLTg0YjEtMzQ5OGYwMGUyMzZjL3JlY29yZGluZ3MuemlwIiwicXVlcnkiOiJpZD03YzE0MWMzMi03YThkLTQxMWMtOTQyOC03MGQxNmRlOWE5ZWEiLCJleHAiOjE4NjkyMjA3NzkuMjEzMDEzNn0.xfR9ZqOWmql1EmAkqc_mszL63hER_s8HziAzfn89-QI) with a minimalist code:
```
from pupil_labs.neon_recording import load
recording = load(data_path)

print(f"Gaze data is OK:\n{recording.gaze.data}")
print(f"Eye state data is empty:\n{recording.eye_state.data}")
```
The ouputs show eye state data is absent while gaze data can be loaded:
```
Gaze data is OK:
[(1.68085799e+09, 684.4744 , 482.6422 )
 (1.68085799e+09, 684.25995, 482.6473 )
 (1.68085799e+09, 684.4015 , 483.29782) ...
 (1.68085813e+09, 796.1253 , 908.0255 )
 (1.68085813e+09, 796.1386 , 908.64374)
 (1.68085813e+09, 796.12115, 910.4585 )]
Eye state data is empty:
[]
```
The problem seems to arise from that in the native recording file there is no `.raw` and `.time` file pairs while `EyeStateStream` expects them
https://github.com/pupil-labs/pl-neon-recording/blob/f6a2b38cc960941156012086de9b2f8b96777418/src/pupil_labs/neon_recording/stream/eye_state_stream.py#L38-L39

**Comment by domstoppable** [comment]
Those missing files would indicate that eyestate was not calculated at the time of the recording. Please make sure you have the latest version of the Neon Companion app and that "Compute eye state" is enabled in the settings

**Comment by qian-chu** [comment]
> Those missing files would indicate that eyestate was not calculated at the time of the recording. Please make sure you have the latest version of the Neon Companion app and that "Compute eye state" is enabled in the settings

I see! So eye state would not be available in the native data if it wasn't enabled on the companion device. But is there a way to still get that data if it wasn't enabled during recording? Because the "Timeseries Data + Scene Video" download option does give 3d_eye_states.csv, so I imagine on the cloud such info is derived.

**Comment by domstoppable** [comment]
Yes, with the option enabled, eye state is computed from the eye cameras in real-time and saved in the raw format.

IIRC, when uploaded to cloud, the raw files are ignored and eye state is computed (or re-computed) from the eye videos on cloud and saved as csv. It's the same algorithm on the device and on cloud.

I will close this issue now, but if you have other questions, please feel free to post in our [Discord server](https://pupil-labs.com/chat) 😄
